[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pilab-regis"
authors = [
    {name = "Nicolas Delinte", email = "nicolas.delinte@uclouvain.be"},
]
readme="README.md"
description = "Implementation of regis"
keywords = ["registration"]
license = "	GPL-3.0-only"
classifiers = ['Intended Audience :: Science/Research',
                'Natural Language :: English',
                'Programming Language :: Python',
]
dependencies = ['dipy',
                'nibabel',
                'numpy',
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "regis.__version__"}

[tool.setuptools.packages.find]
where = ["src"] 